# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chiral.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63hiral.proto\x12\x06\x63hiral\"\x17\n\x15RequestUserInitialize\"\xa3\x01\n\x13ReplyUserInitialize\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12;\n\x08settings\x18\x03 \x03(\x0b\x32).chiral.ReplyUserInitialize.SettingsEntry\x1a/\n\rSettingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\'\n\x14RequestUserSubmitJob\x12\x0f\n\x07job_ser\x18\x01 \x01(\t\"4\n\x12ReplyUserSubmitJob\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"&\n\x14RequestUserCancelJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"4\n\x12ReplyUserCancelJob\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"*\n\x17RequestUserGetJobStatus\x12\x0f\n\x07job_ids\x18\x01 \x03(\t\"\xa7\x01\n\x15ReplyUserGetJobStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12=\n\x08statuses\x18\x03 \x03(\x0b\x32+.chiral.ReplyUserGetJobStatus.StatusesEntry\x1a/\n\rStatusesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xc8\x02\n\x06\x43hiral\x12N\n\x0eUserInitialize\x12\x1d.chiral.RequestUserInitialize\x1a\x1b.chiral.ReplyUserInitialize\"\x00\x12K\n\rUserSubmitJob\x12\x1c.chiral.RequestUserSubmitJob\x1a\x1a.chiral.ReplyUserSubmitJob\"\x00\x12T\n\x10UserGetJobStatus\x12\x1f.chiral.RequestUserGetJobStatus\x1a\x1d.chiral.ReplyUserGetJobStatus\"\x00\x12K\n\rUserCancelJob\x12\x1c.chiral.RequestUserCancelJob\x1a\x1a.chiral.ReplyUserCancelJob\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chiral_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLYUSERINITIALIZE_SETTINGSENTRY._options = None
  _REPLYUSERINITIALIZE_SETTINGSENTRY._serialized_options = b'8\001'
  _REPLYUSERGETJOBSTATUS_STATUSESENTRY._options = None
  _REPLYUSERGETJOBSTATUS_STATUSESENTRY._serialized_options = b'8\001'
  _REQUESTUSERINITIALIZE._serialized_start=24
  _REQUESTUSERINITIALIZE._serialized_end=47
  _REPLYUSERINITIALIZE._serialized_start=50
  _REPLYUSERINITIALIZE._serialized_end=213
  _REPLYUSERINITIALIZE_SETTINGSENTRY._serialized_start=166
  _REPLYUSERINITIALIZE_SETTINGSENTRY._serialized_end=213
  _REQUESTUSERSUBMITJOB._serialized_start=215
  _REQUESTUSERSUBMITJOB._serialized_end=254
  _REPLYUSERSUBMITJOB._serialized_start=256
  _REPLYUSERSUBMITJOB._serialized_end=308
  _REQUESTUSERCANCELJOB._serialized_start=310
  _REQUESTUSERCANCELJOB._serialized_end=348
  _REPLYUSERCANCELJOB._serialized_start=350
  _REPLYUSERCANCELJOB._serialized_end=402
  _REQUESTUSERGETJOBSTATUS._serialized_start=404
  _REQUESTUSERGETJOBSTATUS._serialized_end=446
  _REPLYUSERGETJOBSTATUS._serialized_start=449
  _REPLYUSERGETJOBSTATUS._serialized_end=616
  _REPLYUSERGETJOBSTATUS_STATUSESENTRY._serialized_start=569
  _REPLYUSERGETJOBSTATUS_STATUSESENTRY._serialized_end=616
  _CHIRAL._serialized_start=619
  _CHIRAL._serialized_end=947
# @@protoc_insertion_point(module_scope)
