[tool.pyright]
include = ["."]
exclude = [
    "**/__pycache__",
    "chiral_client/client/chiral_pb2.*",
    "chiral_client/client/chiral_pb2_grpc.py",
]
ignore = ["src/oldstuff"]

reportAttributeAccessIssue = false

pythonVersion = "3.12"
