# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chiral_client.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chiral_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63hiral_client.proto\x12\x06\x63hiral\"4\n\x16RequestUserCommunicate\x12\x1a\n\x12serialized_request\x18\x01 \x01(\t\"y\n\x14ReplyUserCommunicate\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10serialized_reply\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_errorB\x13\n\x11_serialized_reply2[\n\x06\x43hiral\x12Q\n\x0fUserCommunicate\x12\x1e.chiral.RequestUserCommunicate\x1a\x1c.chiral.ReplyUserCommunicate\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chiral_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTUSERCOMMUNICATE']._serialized_start=31
  _globals['_REQUESTUSERCOMMUNICATE']._serialized_end=83
  _globals['_REPLYUSERCOMMUNICATE']._serialized_start=85
  _globals['_REPLYUSERCOMMUNICATE']._serialized_end=206
  _globals['_CHIRAL']._serialized_start=208
  _globals['_CHIRAL']._serialized_end=299
# @@protoc_insertion_point(module_scope)
